version: '3'
services:
  demo-app-db:
    build: database/
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  demo-app-backend:
    build: backend/
    ports:
      - 5000:5000
    environment:
      - "PORT=5000"
      - "POSTGRES_SERVER=demo-app-db"
      - "POSTGRES_CONNECTION=postgres"
      - "POSTGRES_DB=postgres"
      - "BACKEND_CORS_ORIGINS=*"
    depends_on:
      - "demo-app-db"
    links:
      - "demo-app-db"
    restart: unless-stopped # workaround for db not being ready # TODO: setup wait-for-it for db

  demo-app-frontend:
    build: frontend/
    ports:
      - "80:80"
    depends_on:
     - demo-app-backend
