apiVersion: v1
kind: Service
metadata:
  name: demo-app-backend
  labels:
    demo-app: backend
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  type: LoadBalancer
  selector:
    demo-app: backend