apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      demo-app: frontend
  template:
    metadata:
      labels:
        demo-app: frontend
    spec:
      containers:
      - name: "demo-app-frontend"
        image: "gcr.io/GCP_PROJECT/demo-app-frontend:latest"
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
          requests:
            memory: "128Mi"
            cpu: "250m"
      restartPolicy: "Always"
