apiVersion: v1
kind: Service
metadata:
  name: demo-app-frontend
  labels:
    demo-app: frontend
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  type: LoadBalancer
  selector:
    demo-app: frontend
