apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo-app-ingress
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: demo-app-frontend
          servicePort: 80
      - path: /api/actors
        backend:
          serviceName: demo-app-backend
          servicePort: 5000
